---
title: '`r params$hw_title`'
subtitle: "Time Series Analysis (STAT 6391) "
author: 
 - Willliam Ofosu Agyapong^[woagyapong@miners.utep.edu, PhD Data Science, University of Texas at El Paso (UTEP).]
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    fig_caption: true
    keep_tex: yes
    latex_engine: xelatex
    number_sections: no
    toc: false
    # toc_depth: 4
    extra_dependencies: "subfig"
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{amsthm}
- \usepackage{esvect}
- \usepackage{floatrow}
- \usepackage{float}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhf{}
- \rhead{William O. Agyapong}
- \lhead{`r params$hw_title`}
- \cfoot{\thepage}
- \usepackage{algorithm}
- \usepackage[noend]{algpseudocode}
geometry: margin = 1in
fontsize: 10pt
params:
  hw_title: Homework 10
bibliography: ../references.bib
link-citations: yes
linkcolor: blue
nocite: | 
    @shumway2019time
 
---


```{r setup, include=FALSE}
# Set global options for output rendering
knitr::opts_chunk$set(eval = T, echo = F, warning = F, message = F, 
                      fig.pos = "H", out.extra = "", fig.align = "center",
                      cache = F, comment="")

#----------------- Load required packages
# library(dplyr)
library(knitr)
library(kableExtra)
# library(broom)
library(stats)
library(astsa)

  
#----------------- set the current working directory to the file path
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) 


```




<!-- \noindent\rule{17.5cm}{0.8pt} -->

\newpage

# Problem 6.6 (p. 145)

 
# Problem 6.7 (p. 146)

Show that 
$$\frac{\sigma^2_w}{1-\phi^2}(\sum^0_{h=-\infty}(\phi e^{2\pi i\omega})^h + \sum^{\infty}_{h=1}(\phi e^{-2\pi i\omega})^h ) = \frac{\sigma^2_w \phi^{|h|}}{1-\phi^2}$$

\newpage 

<!-- - Robert H. Shumway, & David S. Stoffer. (2019). Time Series: A Data Analysis Approach Using R. -->

# Appendix R Codes for the Analysis {-}
<!-- all R codes are extracted into this chunk -->
```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}

```


# References{-} 







